---
dotfile_files:
  - .ackrc
  - .agignore
  - .clipper.json
  - .config/ranger
  - .ghci
  - .gitattributes
  - .gitignore
  - .gitk
  - .gvimrc
  - .hgrc
  - .imapfilter
  - .inputrc
  - .lbdbrc
  - .mutt
  - .npmrc
  - .pypirc
  - .rdebugrc
  - .rspec
  - .screenrc
  - .tmux.conf
  - .urlview
  - .vim
  - .zsh
  - .zshenv
  - .zshrc
  # - .hammerspoon

dotfile_templates:
  - .config/karabiner/karabiner.json
  - .corpusrc
  - .gemrc
  - .gitconfig
  - .imapfilter/config.lua
  - .mbsyncrc
  - .msmtprc
  - .mutt/config/settings.mutt
  - .mutt/hooks/presync.sh
  - .notmuch-config
  # - .hammerspoon/iterm.lua

git_user_email: 'vsr625@gmail.com'
git_user_name: 'vsr625@gmail.com'

imap_nickname: ISP
imap_server: imap.example.com
imap_user: user@example.com
imap_keychain_account: user@example.com
imap_keychain_name: example.com

smtp_server: smtp.example.com
smtp_from: user@example.com
smtp_user: user@example.com
smtp_keychain_account: user@example.com
smtp_keychain_name: example.com
